### ISSUE TITLE
timeline charts buggy when tab is not on focus

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#101]
The appearing and disappearing bards from the timeline charts do not behave correctly, apparently when the tab looses focus.

Animation to be corrected, otherwise perhaps the solution is to disable them when tab looses focus, then redraw the charts on focus.

To be further investigated.

**Comment by mef** [comment]
Read also:

* [d3.js transition() not working when browser is minimised](http://stackoverflow.com/a/13748965/1006854)
* [Animations pause when browser tab is not visible](http://greensock.com/forums/topic/10051-animations-pause-when-browser-tab-is-not-visible/)

**Comment by mef** [comment]
The top hashtags / mentions also looks to be suffering from the same problem: opacity fade-in transition does not always happen when the tab is not in focus... related to  #100

**Comment by mef** [comment]
@11digitlabs Would the following logic work?

* If tab is in focus then animate (transition) visualizations
* Else just update the DOM at once, without animation.

If technically feasible, it would allow to use the dashboard in the background / on the side, while working on some other window...

**Comment by mef** [comment]
*bump* @11digitlabs 

I think your experience with "tab visibility manager" could help here.

**Comment by 11digitlabs** [comment]
Hey @mef . Sorry for disappearing. I believe that your idea could work, I'll give it a try and let you know

**Comment by 11digitlabs** [comment]
Mehdi, I'll make a branch for this issue and delete all the lines about transitions/delays and give it a try

I just did a quick one for the last 30 minutes chart, it seems to behave ok, nothing strange, except the fact that the two graphs are not syncronized

On the left is a not focused tab (while I was writing this message) and on the right is the open tab
![twitto be - realtime tweets dashboard 2016-10-05 13-07-52](https://cloud.githubusercontent.com/assets/2484390/19109151/cc954372-8afc-11e6-84df-af185abfae8c.png)

As you can see, the per second graph is different

**Comment by 11digitlabs** [comment]
@mef can you please have a look at my commit? I found out that setting delay to 0 is the same as not having a transition at all

**Comment by 11digitlabs** [comment]
Just did one more commit with if/else for the transitions. It doesn look optimal, but with the chaining in d3, what else can we do?

Last commit seems to work ok

**Comment by mef** [comment]
> nothing strange, except the fact that the two graphs are not syncronized
>
On the left is a not focused tab (while I was writing this message) and on the right is the open tab
![twitto be - realtime tweets dashboard 2016-10-05 13-07-52](https://cloud.githubusercontent.com/assets/2484390/19109151/cc954372-8afc-11e6-84df-af185abfae8c.png)

This must just be a minor side effect, caused by the fact that the two pages have not been loaded exactly at the same time. Each starts aggregating messages per second on its own schedule. There must be the same total on each side (plus or minus the 60 seconds ago count).

**Comment by mef** [comment]
@11digitlabs I still have issues with the chart on firefox, cf screenshot:

![screenshot - 081016 - 20 53 31](https://cloud.githubusercontent.com/assets/925443/19215265/5faee958-8d99-11e6-9fd2-c5bbaf84e3d0.png)

**Comment by 11digitlabs** [comment]
@mef the scale has double the values? Do you see any other problems?
I havent faced this issue neither on FF or Chrome

**Comment by 11digitlabs** [comment]
Reverting the changes in branch 3.0.0

**Comment by 11digitlabs** [comment]
Done

**Comment by mef** [comment]
Should be fixed, problem seemed to be with the id of records, not browser's active / inactive states...

To be more precies: the problem of bars jumping around right after appearing is solved. There is still an issue with some of the bars not getting their full height.

This latter issue is probably caused by the fact that bars  have both their y position and height animated at the same time when appearing.

**Comment by mef** [comment]
animations should behave better now too :)
