### ISSUE TITLE
Comparisons - Filtering

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#109]
Saturday night, I had this idea in my head, I woke up and wrote it down not to forget :P

We could do add some VS and filtering functionality 
- Allow users to choose a province and see stats only for that province
- Users could compare stats between provinces
- See only tweets/stats with specific hashtags - mentions (out of the top x tags)

**Comment by mef** [comment]
> We could do add some VS

Serious question: what's a VS?

**Comment by 11digitlabs** [comment]
VS = versus
Brussels VS Liege

**Comment by mef** [comment]
Should I read "some vs and" then, like or/and filters?

**Comment by 11digitlabs** [comment]
And/or, indeed

**Comment by mef** [comment]
not relevant anymore in v4, since the map is removed, and most tweets are not geolocated anymore anyway. Closing.
