### ISSUE TITLE
auto tweet trends

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#112]
Every hour, send automated tweets doing a recap of the top hashtags and mentions from the past hour.

Same for top hashtags / mentions of the day.

**Comment by 11digitlabs** [comment]
And we are ready
Here is a preview of tweets, two hourly and one daily. 

IMPORTANT, get the latest params.json and set `, "enable_tweets": false`
You don't want to start spamming from your localhost :)

Please have a look at tweetBot.js and let me know if you think that we need to resend the tweet if there is an error

![twitter 2016-10-11 14-43-56](https://cloud.githubusercontent.com/assets/2484390/19269620/3e48083a-8fc4-11e6-8d1d-2cde261b05d8.png)

In the screenshot above, you dont see proper hashtags and mention, on purpose. Didnt want to spam them before twitto gr is live :)

**Comment by 11digitlabs** [comment]
@mef why am I getting this error? I have auto tweet disabled btw
![image](https://cloud.githubusercontent.com/assets/2484390/19271250/7d4d9038-8fcc-11e6-9dc6-42ec9a016093.png)

**Comment by mef** [comment]
Child process crashed

**Comment by 11digitlabs** [comment]
Strange, cause it actually does nothing... It just crashed again
Will check

**Comment by 11digitlabs** [comment]
@mef please test, merged in 3.0.0

**Comment by 11digitlabs** [comment]
@mef fixes are merges in 3.0.0

**Comment by mef** [comment]
Heads-up @11digitlabs : I have modified the structure of params.json. Please refer to updated sample files.

**Comment by mef** [comment]
Dry run looks to be running correctly, for the hourly. Good job
