### ISSUE TITLE
Horizontal Bars - Combo hashtag/mention

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#115]
I was thinking that we could have one more set of horizontal bars, and we store

```
10 #hashtagx / @mention
6 #hastagy / @mentiony
```

ping @mef

**Comment by mef** [comment]
I don't understand which information would be displayed.

Pairing hashtags with mentions?

**Comment by 11digitlabs** [comment]
Exactly

**Comment by mef** [comment]
So a bar would show that `#banana` is 3 times more popular than `@someRandomGuy`? 

What would be the usefulness of this information?

How would you decide which hashtag to pair with which mention?

**Comment by mef** [comment]
not relevant anymore in v4, closing the ticket.
