### ISSUE TITLE
Trends do not refresh

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#118]
I left my laptop running with Greece json file since Saturday evening.
Server was still running this morning, and when I visited the local app, mentions and hashtags count was really low.

Numbers were ok once the node server was restarted

**Comment by mef** [comment]
Problem also observed in production server: 

hashtag stats were kind of steady, with top hashtags similar as those from one week ago. Restarting the server corrected the data.

One of the issues is probably that the stats are not cleared at the same time as the old data gets cleaned up.
