### ISSUE TITLE
Blacklist of spam / flood users

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#119]
There are a lot of "spam" tweets with specific hashtags, that apparently screw up the trends.
As @mef suggested, we can introduce a blacklist of user_ids and do not calculate stats for them

![image](https://cloud.githubusercontent.com/assets/2484390/19229671/fa9fd9ec-8ed7-11e6-9d5f-e16c9a22179b.png)

**Comment by mef** [comment]
Implemented.

screen names should be added to the blacklist inside params.json, rather than ids. (cf structure illustrated in sample params file)
