### ISSUE TITLE
Top 3 trends - Order changes but not the sizes

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#125]
When the trends are reshuffled the sizes are not changed
![image](https://cloud.githubusercontent.com/assets/2484390/19265034/2094f14e-8fac-11e6-9d43-bad1aa0b73d2.png)

Related issue #124

**Comment by mef** [comment]
oh indeed lol.

**Comment by mef** [comment]
fixed :)
