### ISSUE TITLE
Top hashtags should be stored lowercase

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#126]
Hashtags with different cases, are considered different in the bar chart, but they are not. For twitter they are the same

So we will need to lowercase them before we store them

![active 2016-10-12 13-16-27](https://cloud.githubusercontent.com/assets/2484390/19306399/286f720e-907e-11e6-9096-4baf9918c9fc.png)

**Comment by mef** [comment]
This is problematic for acronym hashtags, which rather fit in their uppercase form....

**Comment by mef** [comment]
I'd recommend to close this issue for the moment, unless someone wants to implement some fancy [NLP](https://en.wikipedia.org/wiki/Natural_language_processing) solution...
