### ISSUE TITLE
server down: memory limit issue

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#73]
The following error keeps happening on the twitto.be sever

(inside php-fpm log):

````
[16-Dec-2015 09:04:18 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 3470940 bytes) in /media/dbStorage/websites/twitto.be/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php on line 12
````

**Comment by 11digitlabs** [comment]
If I remember correctly we are parsing a huge json file, so seems normal to
consume that much memory to parse.

Could you increase the memory limit and see if it helps?

**Comment by mef** [comment]
Indeed.

Problem I have is: the limit in php.ini is overriden somewhere (probably in the laravel app), need to find out where that happens...

**Comment by mef** [comment]
temporarily worked around the issue by deleting the following content:
* `app/storage/cache/*`
* `app/storage/sessions/*`
* `app/storage/logs/*`
