### ISSUE TITLE
setup skeleton-framework as a submodule

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#77]
A custom build of [skeleton framework](https://github.com/skeleton-framework/skeleton-framework) should be used for twitto's UI.

To be hosted in Mango-is' [fork](https://github.com/Mango-information-systems/skeleton-framework), in a new branch (`twitto_be`?)

- [x] create new branch of skeleton-framework (aligned to skeleton-framework/skeleton-framework master)
- [x] add skeleton-framework as a submodule (twitto branch)
- [x] add init script to package.json, for forkers (cf. https://github.com/Mango-information-systems/mango-is-website/blob/master/package.json#L15)
- [x] setup build/watch script (for development use - cf. https://github.com/Mango-information-systems/mango-is-website/blob/master/package.json#L20 )
- [x] add a build script (for production use - cf. https://github.com/Mango-information-systems/mango-is-website/blob/master/package.json#L12)
- [x] ~~customize style~~ #82

**Comment by mef** [comment]
@11digitlabs feel free to change the content above.

**Comment by 11digitlabs** [comment]
@mef I dont have permission commit
I created the branch locally but cannot push my commit

```
Pushing to https://github.com/Mango-information-systems/skeleton-framework.git
remote: Permission to Mango-information-systems/skeleton-framework.git denied to 11digitlabs.
fatal: unable to access 'https://github.com/Mango-information-systems/skeleton-framework.git/': The requested URL returned error: 403
```

**Comment by mef** [comment]
should be fixed now

**Comment by 11digitlabs** [comment]
@mef can you have a look. Seems that I've done it ok. I also created a new issue for the styling

**Comment by mef** [comment]
looks good :)

You just need to have the skeleton.min.css copied to `public/css` (roughly like  [this](https://github.com/Mango-information-systems/skeleton-framework/blob/d2f5155f16096c831f9ca20831cf7202c2972950/package.json#L19)?)

**Comment by 11digitlabs** [comment]
Done. 

I think we should copy the skeleton.min.css from the submodule to the twitto project, everytime we compile the submodule, not only on start

**Comment by mef** [comment]
> 
I think we should copy the skeleton.min.css from the submodule to the twitto project, everytime we compile the submodule, not only on start


Indeed, to do this you may rather put the cp task inside skeleton's build script (cf [mango-is-website](https://github.com/Mango-information-systems/skeleton-framework/blob/d2f5155f16096c831f9ca20831cf7202c2972950/package.json#L19) for an example).

**Comment by 11digitlabs** [comment]
At last :) Now are think we are truly done
