### ISSUE TITLE
Filter belgian tweets

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#80]
check on server side that tweets returned by twitter API are actually located in Belgium

**Comment by mef** [comment]
heads-up @11digitlabs : you will have to delete your persisted tweets when you pull next version of the branch, as I have modified the data structure.

    rm persist/dHdlZXRz

**Comment by 11digitlabs** [comment]
I did it, but I noticed the following

First time you run the app, with the peristent file deleted, the `tweetsCache` in `statsCalculator.js`does not get updated, it keeps on saying that the length is 0

If I checkout this commit 48e0382c26eddb4301ff0ff6111a3ac580775362 then it works well
