### ISSUE TITLE
Customize style

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#82]
- [ ] customize styles under skeleton framework submodule
- [ ] tune dashboard layout under supported viewports

**Comment by mef** [comment]
@11digitlabs do you mind if I revert the commit above using Roboto for the metrics?

Rationale is:
* This is not a financial dashboard, just tweets, so the "funky" way how Raleway displays number seems appropriate. Numbers look sad now.
* One less font to load --> faster page rendering :)

**Comment by 11digitlabs** [comment]
Sure!
