### ISSUE TITLE
show live statistics about the tweets

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#85]
Display a set of metrics / charts related to the tweets:

- [ ] top hashtags
- [ ] top mentions
- [x] stats about tweets (e.g. #replies, etc) (cf. dashboard mockup in #78)

**Comment by mef** [comment]
@11digitlabs As we discussed yesterday:

The big advantage of d3 is the ease and flexibility it offers in the management of data, by allowing consistent transitions. Cf. general update pattern:

* [level I](http://bl.ocks.org/mbostock/3808218) = yuk
* [level II](http://bl.ocks.org/mbostock/3808221)
* [level III](http://bl.ocks.org/mbostock/3808234) = how things should (always) be

**Comment by 11digitlabs** [comment]
Hey @mef . I've done an initial commit, that updates the total and original tweets. My code will be optimised, I just wanted to do something fast.

Except for the duplicates in my code and possible functions that I could create, is there anything you would like to mention?

PS could you add a label "working on it" so that I know what are the tasks I'm currently working on and have started

**Comment by mef** [comment]
> 
Except for the duplicates in my code and possible functions that I could create, is there anything you would like to mention?

looks ok.

**Comment by mef** [comment]
I have just noticed that the "Original" tweets counter is set to NaN whenever the page is loaded and the db is empty. Does not get corrected then, until page reload.

**Comment by 11digitlabs** [comment]
Nan is fixed, all progress bars are updated. Hooray!

**Comment by mef** [comment]
@11digitlabs Here is a suggestion for the top hashtags and mentions: http://bl.ocks.org/charlesdguthrie/11356441

**Comment by 11digitlabs** [comment]
Can I haz a suggestion for the graph too? ​

**Comment by mef** [comment]
I'm working on this one in #87, if that's ok for you

**Comment by 11digitlabs** [comment]
Sure, go ahead!

**Comment by 11digitlabs** [comment]
@mef here is my idea on the hashtags / mentions

I will  create an object
- hashtag  or mention
- counter

Everytime I encounter a hashtag or a mention, I just increase the counter, except the first time that the user visits the site, where I have to go through all of the tweets in the cache , go into the entities/hashtags and entities/user_mentions and calculate these

Any feedback is appreciated

**Comment by mef** [comment]
@11digitlabs retweets never show up from twitter streaming API, I'm guessing it is because geolocated tweets are only original ones. Retweets are not geolocated, and do not convey the original tweet's geo-location.

I propose that we drop the retweetsCount measure for the moment.

We could add it later (2.x) by implementing one or both of these techniques:
* poll back twitter's REST API periodically, to retrieve an updated retweets_count value
* monitor a set of significant and very active twitter users using the twitter streaming API, in addition to tweets geolocated in Belgium.

**Comment by mef** [comment]
>      
Everytime I encounter a hashtag or a mention, I just increase the counter, except the first time that the user visits the site, where I have to go through all of the tweets in the cache , go into the entities/hashtags and entities/user_mentions and calculate these
>
Any feedback is appreciated

yep, good approach

**Comment by 11digitlabs** [comment]
Alright, dropping the retweets, starting with hashtags/mentions

**Comment by mef** [comment]
Hey, suggestion for the mentions chart: the *coolestest* thing would be a treemap composed of people's profile pics, size according to the mentions count. Challenge will be in keeping pics aspect ratio (would need to use clipping in addition to resizing).

I let you see, perhaps this should be put as a suggestion issue, to be done in 2.x, but not yet...

**Comment by 11digitlabs** [comment]
We could do both! I like it

**Comment by mef** [comment]
FYI I'm starting to replace the tweets counter progress bar by a donut chart.

**Comment by mef** [comment]
Released as is, remaining features to be developed in #100
