### ISSUE TITLE
zoomed map sections

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#89]
The geolocated tweets map can be enhanced by adding a zoomed-in section, showing the tweets in some portion(s) of the map.

![img_20160905_135131](https://cloud.githubusercontent.com/assets/925443/18247044/3cd392aa-7370-11e6-810c-02b747fd2473.jpg)

**Comment by 11digitlabs** [comment]
Didn't see this issue, so while working on Greece, I thought that I needed to be able to zoom in.
So I started working on it, and I'm zooming in with double click on areas, or zoom with the mouse.

It works great, and based on the zoom level I can change the radius of the dots so they become smaller when you zoom in 

I'm thinking of changing the width the lines for the map, to become thinner

![image](https://cloud.githubusercontent.com/assets/2484390/19196184/2a7494c2-8cbd-11e6-8248-858563ba646e.png)


Do you like my approach? Sorry I didnt see the issue before, maybe we start with what I have and we extend

**Comment by mef** [comment]
Yep, looks good.

Do you have an idea about how to let visitors know that the map is zoomable?

**Comment by 11digitlabs** [comment]
Was thinking of a plus/minus sign on the top right of the box plus keeping the mouse zoom in/out
Lets see

**Comment by 11digitlabs** [comment]
I've done my first commit. Have a look when you can. The issues that we currently have is

- When a new tweet comes in, the map is recentered
- When dragged after recentered, the zoom level is applied again
- Need to figure out a way to change the radious of new dots based on the zoom level

Done for tonight, it was a nice session and enjoyed it very much :)

**Comment by mef** [comment]
pretty neat, good job :)
